// Generated by phase1-extract.ts — DO NOT EDIT manually.
// Source: prompt-builder.ts lines 292-344

export const INSURANCE_PRESETS: Record<string, { status: string; detail: string }> = {
  private_only: {
    status: 'private pay right now',
    detail: "happy to give ya a receipt for your claim",
  },
  sgi_approved: {
    status: 'SGI approved',
    detail: "we can bill SGI directly — just bring your claim number",
  },
  all_insurance: {
    status: 'set up with most insurance providers',
    detail: "just let us know who you're with and we'll handle the billing",
  },
  waiting_approval: {
    status: 'private pay for now',
    detail: "we're working on getting set up with insurance, but we can give ya a receipt for your claim",
  },
  not_applicable: {
    status: 'cash or card',
    detail: "we keep it simple — pay when the job's done",
  },
}

// ── Pricing policy map ───────────────────────────────────────────────────────

export const PRICING_POLICY_MAP: Record<string, string> = {
  quote_range:
    'PRICING: If asked for pricing, give a general ballpark range based on typical jobs in your area. ' +
    "Be honest that it depends on the specifics and you'll have someone call back with a firm quote.",
  no_quote_callback:
    "PRICING: Never quote prices. If a caller asks about cost, say you'll have someone call them back " +
    'with an accurate quote — pricing varies by job.',
  website_pricing:
    'PRICING: For pricing questions, direct callers to the website. ' +
    "Say you'd rather give them accurate numbers than guess on the phone.",
  collect_first:
    "PRICING: If asked about pricing, collect the caller's information first. " +
    "Only give a rough range after their details are captured — this helps give them accurate numbers.",
}

// ── Unknown answer behavior map ──────────────────────────────────────────────

export const UNKNOWN_ANSWER_MAP: Record<string, string> = {
  take_message:
    "FALLBACK: When you don't know the answer to a question, take a message and tell the caller " +
    "someone will call them back with the information.",
  transfer:
    "FALLBACK: When you don't know the answer to a question, offer to transfer the caller to a live " +
    "person who can help.",
  find_out_callback:
    "FALLBACK: When you don't know the answer to a question, say \"let me find out and we'll call " +
    'you back with the answer." Do not guess or make up information.',
}
