// Generated by phase1-extract.ts — DO NOT EDIT manually.
// Source: prompt-builder.ts lines 1888-1921

export const MODE_VARIABLE_OVERRIDES: Record<string, {
  COMPLETION_FIELDS?: string
  CLOSE_ACTION?: string
  FIRST_INFO_QUESTION?: string
  INFO_TO_COLLECT?: string
  FORBIDDEN_EXTRA?: string
  TRIAGE_DEEP?: string
}> = {
  voicemail_replacement: {
    COMPLETION_FIELDS: "caller's name, phone number, and a brief message",
    CLOSE_ACTION: 'tell them someone will call back shortly',
    FIRST_INFO_QUESTION: 'your name?',
    INFO_TO_COLLECT: 'name, phone, brief message',
    FORBIDDEN_EXTRA: 'Do not triage or diagnose. You may confirm services or hours in one sentence if asked — then immediately redirect to message-taking. Collect name, phone, and a brief message only.',
    TRIAGE_DEEP: "Ask for the caller's name, phone number, and a brief message. Do not ask about services, schedules, or urgency.",
  },
  info_hub: {
    COMPLETION_FIELDS: "caller's name and phone number (only if they request a callback)",
    CLOSE_ACTION: 'answer their questions; offer callback if they want follow-up',
    FIRST_INFO_QUESTION: 'What can I help you with today?',
    INFO_TO_COLLECT: 'name and phone (only if callback requested)',
    FORBIDDEN_EXTRA: 'Answer questions before asking for contact info. Only request name and phone if the caller wants a callback.',
    TRIAGE_DEEP: 'Ask the caller what they\'d like to know: "What can I help you with today?" Answer from the PRODUCT KNOWLEDGE BASE. Do not push through a triage script.',
  },
  appointment_booking: {
    COMPLETION_FIELDS: "caller's name, phone number, service type, and preferred date/time",
    CLOSE_ACTION: 'book an appointment right now on this call',
    FIRST_INFO_QUESTION: 'What service are you looking for and what day works?',
    INFO_TO_COLLECT: 'name, phone, service type, preferred date/time',
    FORBIDDEN_EXTRA: 'Do not close without attempting to book. Lead every call with: "I can check availability and book you right now — what service are you looking for?" Drive to checkCalendarAvailability on this call. Never end without either a booking confirmed or a specific date/time collected.',
    TRIAGE_DEEP: 'Lead with booking ability. Open with: "I can check availability and book you right now — what service were you looking for?" Call checkCalendarAvailability on the same call. Do not push through a long triage script before offering to book.',
  },
  // lead_capture: no overrides — defers entirely to niche/template/call_handling_mode
}
