// Generated by phase1-extract.ts — DO NOT EDIT manually.
// Source: prompt-builder.ts lines 1162-1178
//
// Per-niche HOT/WARM hints only. COLD + JUNK are governed by the base classifier
// RULES (see openrouter.ts buildSystemPrompt) — "real humans are never JUNK".
// Every niche rule defers off-topic / real-human-not-matching cases to COLD with
// full content capture. JUNK is reserved for silence and robocalls.

// ── Per-niche classification rules (for call classifier) ─────────────────────

export const NICHE_CLASSIFICATION_RULES: Record<string, string> = {
  auto_glass: 'HOT = urgent windshield/chip repair, same-day need. WARM = price check, callback requested, no urgency. Any other live caller (off-topic, wrong-number-with-conversation, vendor, personal) → COLD with content captured. JUNK = silence or robocall only.',
  hvac: 'HOT = system broken now, no heat or AC, emergency. WARM = service inquiry, maintenance, callback wanted. Any other live caller → COLD with content captured. JUNK = silence or robocall only.',
  plumbing: 'HOT = flooding, burst pipe, no water — active emergency. WARM = service request, routine repair, callback wanted. Any other live caller → COLD with content captured. JUNK = silence or robocall only.',
  dental: 'HOT = tooth pain, dental emergency, needs appointment today. WARM = booking inquiry, new patient. Any other live caller → COLD with content captured. JUNK = silence or robocall only.',
  legal: 'HOT = urgent legal matter, court deadline imminent. WARM = consultation request, active legal situation, callback wanted. Any other live caller → COLD with content captured. JUNK = silence or robocall only.',
  salon: 'HOT = wants to book now or same day. WARM = availability check, price inquiry, future booking intent. Any other live caller → COLD with content captured. JUNK = silence or robocall only.',
  real_estate: 'HOT = ready to list or buy now, has specific property. WARM = market assessment, actively looking, wants agent callback. Any other live caller (friends, family, vendors, personal calls, off-market questions, wrong-number-with-conversation) → COLD with content captured — the agent is also a receptionist for the realtor. JUNK = silence or robocall only.',
  property_management: 'HOT = maintenance emergency (flooding, no heat, gas leak, fire, security). WARM = routine maintenance, viewing inquiry, billing/rent question, tenant follow-up, returning tenant with update. Any other live caller (vendor pitch, personal call for owner, friend, wrong-number-with-conversation) → COLD with content captured. JUNK = silence or robocall only.',
  outbound_isa_realtor: 'HOT = expresses immediate buying/selling intent, wants to meet agent. WARM = interested but not ready, wants callback at specific time. COLD = not interested, maybe later, or any live human off-script. JUNK = DNC + hangup, or pure silence.',
  voicemail: 'HOT = urgent, time-sensitive, caller stressed or mentioned deadline. WARM = left message, wants callback, standard inquiry. COLD = no message left, hung up after greeting, or any off-topic real caller. JUNK = silence or robocall only.',
  print_shop: 'HOT = urgent deadline (event today or tomorrow, rush), ready to order. WARM = price inquiry, reorder, order status check, callback. Any other live caller (off-topic, wrong number with conversation, vendor) → COLD with content captured. JUNK = silence or robocall only.',
  barbershop: 'HOT = same-day booking, urgent cut for an event, calendar-booked. WARM = booking inquiry, price+intent, walk-in question that converts. Any other live caller → COLD with content captured. JUNK = silence or robocall only.',
  other: 'HOT = immediate need, urgency signals, ready to proceed. WARM = interested, callback requested. COLD = info only, off-topic, personal call, wrong-number-with-conversation, any real human without HOT/WARM signals. JUNK = silence or robocall only.',
}
