// Generated by phase1-extract.ts — DO NOT EDIT manually.
// Source: prompt-builder.ts lines 1162-1178

// ── Per-niche classification rules (for call classifier) ─────────────────────

export const NICHE_CLASSIFICATION_RULES: Record<string, string> = {
  auto_glass: 'HOT = urgently needs windshield/chip repair or same-day service. WARM = price inquiry, callback requested, no urgency. COLD = general question, no booking intent. JUNK = spam, wrong number, silence.',
  hvac: 'HOT = system broken now, no heat or AC, emergency. WARM = service inquiry, maintenance request, callback wanted. COLD = general info only, no urgency. JUNK = spam or wrong number.',
  plumbing: 'HOT = flooding, burst pipe, no water — active emergency. WARM = service request, callback wanted, routine repair. COLD = price inquiry only, no timeline. JUNK = spam or wrong number.',
  dental: 'HOT = tooth pain, dental emergency, needs appointment today. WARM = booking inquiry, new patient wanting appointment. COLD = general info about services, no urgency. JUNK = spam.',
  legal: 'HOT = urgent legal matter, court deadline imminent, emergency situation. WARM = consultation request, callback wanted, active legal situation. COLD = general info inquiry only. JUNK = spam.',
  salon: 'HOT = wants to book appointment now or same day. WARM = availability check, price inquiry, future booking intent. COLD = general questions only. JUNK = spam.',
  real_estate: 'HOT = ready to list or buy now, has specific property in mind. WARM = market assessment wanted, actively looking, wants agent callback. COLD = casual browsing inquiry. JUNK = spam.',
  property_management: 'HOT = maintenance emergency (flooding, no heat, gas leak, fire, security). WARM = routine maintenance request, viewing inquiry, billing question. COLD = general inquiry only. JUNK = spam.',
  outbound_isa_realtor: 'HOT = expresses immediate buying/selling intent, wants to meet agent. WARM = interested but not ready, wants callback at specific time. COLD = not interested, maybe later. JUNK = DNC request, wrong contact, hang-up.',
  voicemail: 'HOT = urgent matter, time-sensitive, caller stressed or mentioned deadline. WARM = left message, wants callback, standard inquiry. COLD = no message left, hung up or no reason given. JUNK = spam, robocall, wrong number.',
  print_shop: 'HOT = urgent deadline (event today or tomorrow, rush needed), ready to order with artwork in hand. WARM = price inquiry, reorder, order status check, callback requested. COLD = general info only, no urgency or order intent. JUNK = spam, wrong number, vendor pitch.',
  barbershop: 'HOT = same-day booking needed, urgent cut for an event, or booked live via calendar. WARM = booking inquiry, price question with booking intent, walk-in question that converts. COLD = general info only, no booking intent. JUNK = spam, wrong number, telemarketer.',
  other: 'HOT = immediate need, urgency signals, ready to proceed. WARM = interested, callback requested. COLD = info only, no intent signals. JUNK = spam or wrong number.',
}
