// Generated by phase1-extract.ts — DO NOT EDIT manually.
// Source: prompt-builder.ts lines 352-1160

type NicheDefaults = Record<string, string>

export const NICHE_DEFAULTS: Record<string, NicheDefaults> = {
  _common: {
    OWNER_PHONE: '',
    TRANSFER_ENABLED: 'false',
    SERVICES_NOT_OFFERED: '',
    sms_template: "Thanks for calling {{business}}! We'll call you back shortly.",
  },
  auto_glass: {
    INDUSTRY: 'auto glass shop',
    PRIMARY_CALL_REASON: 'windshield repair or replacement',
    SERVICE_APPOINTMENT_TYPE: 'service appointment',
    TRIAGE_SCRIPT: [
      `"If chip: 'gotcha, just a chip? we can usually fix those if it's smaller than a quarter.'"`,
      `"If crack or smashed: 'oof, yeah that sounds like a full replacement.'"`,
      `"If price asked: 'i can get ya a quick quote — what year, make, and model is it?'"`,
      `"If ADAS/camera question: 'do you know if it's got that lane assist camera up by the mirror?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what year, make, and model is it?',
    INFO_TO_COLLECT: 'year, make, model, and whether they have the lane assist camera',
    INFO_LABEL: 'vehicle info',
    SERVICE_TIMING_PHRASE: 'bring it in',
    CLOSE_PERSON: 'the boss',
    CLOSE_ACTION: 'call ya back with a quote and to confirm your slot',
    MOBILE_POLICY: "you'd bring it to us",
    COMPLETION_FIELDS: 'vehicle year, make, model, and preferred timing',
    INSURANCE_STATUS: 'private pay right now',
    INSURANCE_DETAIL: "happy to give ya a receipt for your claim",
    WEEKEND_POLICY: "yeah we're open saturdays too. sundays we can sometimes do depending on how urgent it is",
    FORBIDDEN_EXTRA: [
      "NEVER apologize for being AI or act uncertain about your role. You are {{AGENT_NAME}} — confident and matter-of-fact about what you are.",
      "Always say \"v-i-n\" (spell it out), never \"vin.\"",
    ].join('\n'),
    FILTER_EXTRA: `INSURANCE / BILLING QUESTION:
"we work with SGI and also do regular payment. let me grab your vehicle info and the team will sort out the details for you."
then continue to triage and vehicle info. If hesitant or more questions: "no problem — I'll have {{CLOSE_PERSON}} call you back with more details." then use hangUp tool.

DELIVERY or PACKAGE:
"perfect — just head around to the back door, someone will meet you there. I'll let the team know." then use hangUp tool.

ASKING FOR {{CLOSE_PERSON}} / THE OWNER BY NAME:
"{{CLOSE_PERSON}}'s not available right now but I can have them call you back. What's your name and what year, make, and model is it?"
Then continue to vehicle details as normal. If they don't want to give vehicle info: "no problem — I'll have {{CLOSE_PERSON}} call you back at the number you're calling from. talk soon." then use hangUp tool.`,
    TRIAGE_DEEP: `TRIAGE (Windshield)
If "chip": "gotcha, just a chip? we can usually fix those if it's smaller than a quarter."
If "crack" or "smashed": "oof, yeah that sounds like a full replacement."
If price asked: "I can get you a quick quote — what year, make, and model is it?"

VEHICLE DETAILS
If not given yet: "what year, make, and model is it?"
If given: "okay, just to confirm — that's a [year] [make] [model], right?"

SENSOR CHECK (Skip for non-windshield or delivery)
"do you know if it's got that lane assist camera up by the mirror?"
Yes: "alright, that means we'll need to calibrate it. if you've got the v-i-n handy that helps, otherwise no worries."
No or don't know: "no stress, we can check when you get here."

SCHEDULING
"when were you looking to bring it in?"
Any date given: "perfect — I've noted that. I'll have {{CLOSE_PERSON}} check the schedule and call you back to confirm."
(Never say "it's open" or "we have a spot")

Weekend asked: "yeah we're open saturdays too. sundays we can sometimes do depending on how urgent it is — want me to flag it?"

Yes: "okay, I'll flag it. {{CLOSE_PERSON}} will call you back to sort out a time."
No: "got it, we'll stick to the regular schedule then."`,
    NICHE_EXAMPLES: `Example A — Caller gives vehicle + urgency upfront (CLOSE fast):
Caller: "hi yeah I need my windshield replaced today, it's a 2022 Honda Civic"
You: "got it — a 2022 Honda Civic, need it done today. does it have that lane assist camera up by the mirror?"
Caller: "yeah it does"
You: "perfect — I'll flag it urgent. I'll have {{CLOSE_PERSON}} call you back right away to get you on the schedule."
[Caller gave vehicle + timing. Collect sensor info then close immediately — don't ask follow-up questions.]

Example B — Caller asks for owner, refuses vehicle info:
Caller: "I just want to talk to the owner directly"
You: "no problem — they're not available right now but I can have them call you back. what year, make, and model is it?"
Caller: "I'd rather just wait for them to call"
You: "no problem at all — I'll have {{CLOSE_PERSON}} call you back at the number you're calling from. talk soon." [hangUp]
[One light attempt for vehicle info. If they decline, close immediately. Never push twice.]

Example C — Chip vs crack triage:
Caller: "I've got a crack in my windshield"
You: "oof yeah — how long is it roughly? like a small crack or is it spreading across the glass?"
Caller: "it's pretty big, goes across most of it"
You: "yeah that sounds like a full replacement. what year, make, and model is it?"
[Triage first to set expectations, then move to vehicle details.]

Example D — Sensor check, caller doesn't know:
Caller: "2021 Toyota Camry, needs a full replacement"
You: "got it — do you know if it's got that lane assist camera up by the mirror?"
Caller: "I have no idea honestly"
You: "no stress — we can check when you get here. when were you looking to bring it in?"
[Never make caller feel bad for not knowing. Move straight to scheduling.]

Example E — Spam robocall:
Caller: [pre-recorded voice] "...your vehicle's extended warranty is about to expire..."
You: "thanks, not interested. have a good day." [use hangUp immediately — do not engage]`,
  },
  hvac: {
    INDUSTRY: 'heating and cooling company',
    PRIMARY_CALL_REASON: 'heating or cooling issue',
    SERVICE_APPOINTMENT_TYPE: 'service call',
    TRIAGE_SCRIPT: [
      `"If heating: 'gotcha, furnace trouble. is it not turning on at all, or just not heating right?'"`,
      `"If cooling: 'okay, AC issue. is it not blowing cold, or not running at all?'"`,
      `"If maintenance/tune-up: 'for sure — seasonal tune-up. what type of unit is it — furnace, central AC, or both?'"`,
      `"If not sure: 'no worries — what's happening? describe it for me and we'll figure it out.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what type of system is it — furnace, AC, or both?',
    INFO_TO_COLLECT: "type of system, what's happening, how old the unit is, and preferred timing",
    INFO_LABEL: 'system info',
    SERVICE_TIMING_PHRASE: 'get someone out there',
    CLOSE_PERSON: 'our technician',
    CLOSE_ACTION: 'call ya back to schedule the service visit',
    MOBILE_POLICY: 'we come to you',
    COMPLETION_FIELDS: 'type of system, the issue, and preferred timing',
    INSURANCE_STATUS: 'cash or card',
    INSURANCE_DETAIL: "we keep it simple — pay when the job's done",
    WEEKEND_POLICY: 'we handle emergency calls on weekends',
    FORBIDDEN_EXTRA: [
      "NEVER diagnose over the phone — collect the symptoms and route to technician callback.",
      "NEVER quote specific repair or install prices — always route to {{CLOSE_PERSON}} callback.",
      "If caller says no heat in winter, ALWAYS flag as [URGENT] — do not ask if it's an emergency.",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
NO HEAT / NO AC / SYSTEM NOT RUNNING:
"okay, that's definitely urgent — is it completely off, or is it running but not heating/cooling?"
→ Completely off or no heat in winter: flag [URGENT] → collect name + address → close fast
→ Running but not working right: collect name + address + symptoms → close normally
STRANGE NOISE / SMELL / LEAK:
"got it — is it a burning smell, a gas smell, or something else?"
→ Gas smell: "okay — call your gas company emergency line right now and get everyone out. what's your name and address so {{CLOSE_PERSON}} can follow up?"
→ Burning smell: flag [URGENT] → collect name + address → close fast
→ Other: collect name + address + description → close normally
MAINTENANCE / TUNE-UP:
"for sure — seasonal tune-up. furnace, AC, or both?"
→ Collect: system type + name + address + preferred timing → close normally
NEW INSTALL / QUOTE:
"got it — what are you looking to get installed?"
→ Collect: what they want + name + address → close normally`,
    NICHE_EXAMPLES: `Example A — No heat emergency (winter):
Caller: "my furnace isn't working and it's freezing"
You: "okay, flagging this urgent right now. what's your name and address?"
Caller: [name and address]
You: "got it — {{CLOSE_PERSON}}'ll call you back right away. talk soon." [use hangUp — flag [URGENT]]

Example B — AC not cooling:
Caller: "my AC is running but it's not blowing cold air"
You: "gotcha — how long has it been doing that?"
Caller: "since yesterday"
You: "okay, let me grab your info. what's your name and address?"
[Collect info, route to callback. Don't diagnose.]

Example C — Seasonal tune-up:
Caller: "I want to get my furnace serviced before winter"
You: "for sure — smart move. is it a furnace only, or furnace and AC?"
Caller: "just the furnace"
You: "got it. what's your name and address, and when works best for you?"

Example D — Gas smell (life safety):
Caller: "I smell gas near my furnace"
You: "okay — call your gas company emergency line right now and get everyone out of the house. what's your name and address so {{CLOSE_PERSON}} can follow up?"
[Life safety = gas company / 9-1-1 first. Still collect info for follow-up.]`,
  },
  plumbing: {
    INDUSTRY: 'plumbing company',
    PRIMARY_CALL_REASON: 'plumbing issue or repair',
    SERVICE_APPOINTMENT_TYPE: 'service call',
    TRIAGE_SCRIPT: [
      `"If emergency (flooding, no water, burst pipe): 'okay, sounds urgent. is this an active leak or no water at all?'"`,
      `"If routine: 'got it. is it a repair, install, or do you need someone to take a look first?'"`,
      `"If drain/clog: 'gotcha, clogged drain. is it one drain or multiple drains backing up?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: "what's going on — can you describe the issue?",
    INFO_TO_COLLECT: "what the issue is, where in the house, how long it's been happening, and preferred timing",
    INFO_LABEL: 'job details',
    SERVICE_TIMING_PHRASE: 'get someone out there',
    CLOSE_PERSON: 'our plumber',
    CLOSE_ACTION: 'call ya back to book the service call',
    MOBILE_POLICY: 'we come to you',
    COMPLETION_FIELDS: 'the plumbing issue, location in the house, and preferred timing',
    INSURANCE_STATUS: 'cash or card',
    INSURANCE_DETAIL: "we keep it simple — pay when the job's done",
    WEEKEND_POLICY: 'we handle emergency calls on weekends',
    FORBIDDEN_EXTRA: [
      "NEVER diagnose plumbing problems over the phone — collect the symptoms and route to plumber callback.",
      "NEVER quote specific prices — always route to {{CLOSE_PERSON}} callback for estimates.",
      "If caller reports active flooding or water leak, ALWAYS flag as [URGENT] — do not ask follow-up questions about severity.",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
ACTIVE EMERGENCY (flooding, burst pipe, no water, sewage backup):
"okay, that sounds urgent — is the water still running right now?"
→ Active water: "okay, if you can, turn off the main water shut-off valve. what's your name and address?"
→ flag [URGENT] → collect name + address → close fast
CLOGGED DRAIN / SLOW DRAIN:
"gotcha, clogged drain. is it one drain or multiple drains backing up?"
→ Multiple drains: "that could be a main line issue — let me flag it. what's your name and address?"
→ Single drain: collect name + address + which drain → close normally
REPAIR / INSTALL / GENERAL:
"got it — is it a repair, new install, or do you need someone to take a look first?"
→ Collect: what they need + name + address + preferred timing → close normally
WATER HEATER:
"no hot water, or is it leaking?"
→ Leaking: flag [URGENT] → collect name + address → close fast
→ No hot water: collect name + address → close normally`,
    NICHE_EXAMPLES: `Example A — Active flooding emergency:
Caller: "my basement is flooding right now"
You: "okay — if you can, turn off the main water valve right now. what's your name and address?"
Caller: [name and address]
You: "got it, flagging this urgent — {{CLOSE_PERSON}}'ll call you back right away. talk soon." [use hangUp — flag [URGENT]]

Example B — Clogged drain:
Caller: "my kitchen sink is completely clogged"
You: "gotcha — is it just the kitchen sink, or are other drains slow too?"
Caller: "just the kitchen"
You: "okay, probably a kitchen line clog. what's your name and address?"

Example C — Water heater leaking:
Caller: "my water heater is leaking all over the floor"
You: "okay, that's urgent — can you turn off the water supply to it? what's your name and address?"
[Flag [URGENT]. Collect info and close fast.]

Example D — General plumbing question:
Caller: "I need a new faucet installed in my bathroom"
You: "got it — what's your name and address, and when works best for you?"
[Straightforward install request. Collect info, route to callback.]`,
  },
  dental: {
    INDUSTRY: 'dental office',
    PRIMARY_CALL_REASON: 'dental appointment or tooth issue',
    SERVICE_APPOINTMENT_TYPE: 'appointment',
    TRIAGE_SCRIPT: [
      `"If pain/emergency: 'okay, sounds urgent. are you in pain right now, like can't wait level?'"`,
      `"If cleaning/checkup: 'totally, we can book that. are you a new patient with us or have you been here before?'"`,
      `"If specific procedure: 'got it — i'll have our front desk call ya back with the details. real quick — are you a new or existing patient?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'are you a new patient with us or have you been in before?',
    INFO_TO_COLLECT: 'new or existing patient, what they need, and preferred day or time',
    INFO_LABEL: 'patient info',
    SERVICE_TIMING_PHRASE: 'come in',
    CLOSE_PERSON: 'our front desk',
    CLOSE_ACTION: 'call ya back to book your appointment',
    MOBILE_POLICY: "you'd come in to us",
    COMPLETION_FIELDS: 'new or existing patient, what they need, and preferred timing',
    INSURANCE_STATUS: 'we work with most dental insurance',
    INSURANCE_DETAIL: "just bring your insurance card and we'll sort it out",
    WEEKEND_POLICY: "we're closed weekends — call back monday and we'll get you in",
    FORBIDDEN_EXTRA: [
      "NEVER give medical advice, diagnose conditions, or recommend treatments — route all clinical questions to {{CLOSE_PERSON}} callback.",
      "NEVER quote specific procedure prices — always route to {{CLOSE_PERSON}} for cost estimates.",
      "NEVER confirm or deny appointment availability — always route to {{CLOSE_PERSON}} to check the schedule.",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
DENTAL EMERGENCY / PAIN:
"okay, are you in pain right now — like can't wait level?"
→ Severe pain, broken tooth, knocked out tooth, swelling: flag [URGENT] → "I'm flagging this urgent — what's your name?"
→ Mild/manageable pain: collect name + what's going on + preferred timing → close normally
CLEANING / CHECKUP / ROUTINE:
"totally, we can book that. are you a new patient with us or have you been in before?"
→ New patient: collect name + preferred day/time → close
→ Existing patient: collect name + preferred day/time → close
SPECIFIC PROCEDURE (whitening, veneers, braces, implants, crown):
"got it — {{CLOSE_PERSON}}'ll call you back with the details on that. are you a new or existing patient?"
→ Collect name + new/existing + preferred timing → close
INSURANCE QUESTION:
"we work with most dental insurance — just bring your card when you come in and we'll sort it out. can I get your name to book you in?"`,
    NICHE_EXAMPLES: `Example A — Dental emergency (severe pain):
Caller: "I broke my tooth and I'm in a lot of pain"
You: "okay, flagging this urgent — what's your name?"
Caller: [name]
You: "got it — {{CLOSE_PERSON}}'ll call you back right away to get you in. talk soon." [use hangUp — flag [URGENT]]

Example B — New patient, routine cleaning:
Caller: "I'd like to book a cleaning, I've never been there before"
You: "for sure — welcome! what's your name, and what day works best for you?"
Caller: [name and day]
You: "perfect — {{CLOSE_PERSON}}'ll call you back to confirm your appointment. talk soon." [use hangUp]

Example C — Specific procedure inquiry:
Caller: "how much does teeth whitening cost?"
You: "{{CLOSE_PERSON}}'ll call you back with the details on that — pricing depends on the treatment. can I get your name?"
[Never quote procedure prices. Collect name, route to callback.]

Example D — Insurance question:
Caller: "do you take Blue Cross?"
You: "we work with most dental insurance — just bring your card and we'll sort it out. can I get your name to get you booked in?"`,
  },
  legal: {
    INDUSTRY: 'law firm',
    PRIMARY_CALL_REASON: 'legal question or consultation',
    SERVICE_APPOINTMENT_TYPE: 'consultation',
    TRIAGE_SCRIPT: [
      `"If urgent matter: 'got it. is this something time-sensitive, like a court deadline coming up?'"`,
      `"If general inquiry: 'okay, what area is this regarding — family, real estate, business, or something else?'"`,
      `"If existing client: 'for sure. do you have a file number or the name of the lawyer you've been working with?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what area of law is this regarding?',
    INFO_TO_COLLECT: 'area of law, brief description of the situation, and preferred time for a call back',
    INFO_LABEL: 'case details',
    SERVICE_TIMING_PHRASE: 'book a consultation',
    CLOSE_PERSON: 'one of our lawyers',
    CLOSE_ACTION: 'call ya back to discuss your situation and schedule a consultation',
    MOBILE_POLICY: "you'd come in to our office, or we can do it over the phone",
    COMPLETION_FIELDS: 'area of law, brief situation, and preferred callback time',
    INSURANCE_STATUS: 'we offer a free initial consultation',
    INSURANCE_DETAIL: "the first call is on us — no obligation",
    WEEKEND_POLICY: "we're closed weekends — leave a message and we'll call back first thing monday",
    FORBIDDEN_EXTRA: [
      "NEVER give legal advice, interpret law, or suggest legal strategy — always route to lawyer callback.",
      "NEVER discuss fees, retainers, or billing rates — always route to {{CLOSE_PERSON}} callback.",
      "NEVER confirm or deny case outcomes or likelihood of success.",
      "NEVER discuss details of other clients or cases — strict confidentiality.",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
URGENT / TIME-SENSITIVE MATTER:
"got it — is this something time-sensitive, like a court deadline coming up?"
→ Court deadline or arrest or active legal crisis: flag [URGENT] → collect name + area of law + brief description → close fast
→ Time-sensitive but not crisis: collect name + area of law + brief description + preferred timing → close normally
EXISTING CLIENT:
"for sure — do you have a file number or the name of the lawyer you've been working with?"
→ Collect: name + file number or lawyer name + reason for call → close
NEW CLIENT / GENERAL INQUIRY:
"okay, what area is this regarding — family, real estate, business, criminal, or something else?"
→ Collect: area of law + name + brief description → close
OPPOSING PARTY / SERVED WITH PAPERS:
"I understand — that can be stressful. let me grab your info so one of our lawyers can call you back right away."
→ Collect name + what they were served with → close`,
    NICHE_EXAMPLES: `Example A — Urgent legal matter:
Caller: "I have a court date next week and I don't have a lawyer"
You: "okay, let me flag this urgent. what's your name and what area of law is this — family, criminal, civil?"
Caller: [name and area]
You: "got it — {{CLOSE_PERSON}}'ll call you back right away. talk soon." [use hangUp — flag [URGENT]]

Example B — New client, general inquiry:
Caller: "I'm looking for a lawyer for a real estate matter"
You: "got it — real estate. what's your name, and can you give me a quick idea of what's going on?"
Caller: [name and brief description]
You: "perfect — {{CLOSE_PERSON}}'ll call you back to discuss it. talk soon." [use hangUp]

Example C — Existing client follow-up:
Caller: "I'm an existing client, I need to speak to my lawyer"
You: "for sure — do you have a file number or the name of the lawyer you've been working with?"
Caller: [file number or lawyer name]
You: "got it — I'll pass that along and they'll call you back. talk soon." [use hangUp]

Example D — Asks about fees:
Caller: "how much do you charge for a consultation?"
You: "{{CLOSE_PERSON}}'ll go over fees with you when they call — the first chat is just to understand your situation. can I get your name?"
[Never discuss fees or retainers. Collect name, route to callback.]`,
  },
  salon: {
    INDUSTRY: 'salon',
    PRIMARY_CALL_REASON: 'appointment or booking',
    SERVICE_APPOINTMENT_TYPE: 'appointment',
    TRIAGE_SCRIPT: [
      `"If haircut/color: 'for sure. are you looking for a cut, color, or both?'"`,
      `"If specific service: 'got it. have you been to us before or would this be your first time?'"`,
      `"If walk-in question: 'we do take walk-ins when we have availability, but booking ahead is the best way to guarantee your spot.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what service are you looking to book?',
    INFO_TO_COLLECT: 'what service they want, new or returning client, and preferred day or time',
    INFO_LABEL: 'appointment details',
    SERVICE_TIMING_PHRASE: 'come in',
    CLOSE_PERSON: 'our front desk',
    CLOSE_ACTION: 'call ya back to confirm your appointment',
    MOBILE_POLICY: "you'd come in to us",
    COMPLETION_FIELDS: 'service wanted, new or returning, and preferred timing',
    INSURANCE_STATUS: 'cash or card',
    INSURANCE_DETAIL: "we keep it simple — pay when the service is done",
    WEEKEND_POLICY: 'yeah we do weekend appointments — usually book up fast though',
    FORBIDDEN_EXTRA: [
      "NEVER confirm or deny appointment availability — always route to {{CLOSE_PERSON}} to check the schedule.",
      "NEVER quote specific service prices — always route to {{CLOSE_PERSON}} callback for pricing.",
      "NEVER recommend specific hair products, treatments, or styles — route to stylist callback.",
      "Never promise a specific time WITHOUT first calling checkCalendarAvailability.",
      "If checkCalendarAvailability returns fallback=true or an error: say \"Let me have {{CLOSE_PERSON}} give you a call to sort out a time — can I get your name?\" then route to standard callback flow.",
      "If bookAppointment returns booked=false with slot_taken: say \"Oh, that slot just got taken — I've got [nextAvailable] open instead, does that work?\"",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
HAIRCUT / COLOR / STYLING:
"for sure — are you looking for a cut, color, or both?"
→ Collect: service type + new or returning + preferred day/time + specific stylist request → close
SPECIFIC STYLIST REQUEST:
"do you have a preferred stylist, or are you okay with whoever's available?"
→ If specific stylist: note it → collect name + service + timing → close
WALK-IN QUESTION:
"we do take walk-ins when there's availability, but booking ahead is the best way to guarantee your spot. want me to get you booked?"
→ If yes: collect name + service + preferred timing → close
→ If no: "no worries — just come on by and we'll see what we can do."
PRODUCT QUESTION:
"we carry a range of professional products in the salon — {{CLOSE_PERSON}}'ll help you out with that when they call back. can I get your name?"
CANCELLATION / RESCHEDULE:
"got it — what's your name and when was your appointment? I'll pass that along and {{CLOSE_PERSON}}'ll sort it out."`,
    NICHE_EXAMPLES: `Example A — Booking a haircut:
Caller: "I'd like to book a haircut for Saturday"
You: "for sure — have you been to us before, or would this be your first time?"
Caller: "first time"
You: "welcome! what's your name, and do you have a preferred time on Saturday?"
Caller: [name and time]
You: "perfect — {{CLOSE_PERSON}}'ll call you back to confirm. talk soon." [use hangUp]

Example B — Specific stylist request:
Caller: "I want to book with Sarah for a color appointment"
You: "got it — Sarah for color. what's your name, and what day works for you?"
Caller: [name and day]
You: "perfect — {{CLOSE_PERSON}}'ll check Sarah's schedule and call you back. talk soon." [use hangUp]

Example C — Walk-in question:
Caller: "do you take walk-ins?"
You: "we do when there's availability — but booking ahead is the best way to guarantee a spot. want me to get you set up?"
Caller: "yeah sure"
You: "awesome — what service are you looking for, and what's your name?"

Example D — Price inquiry:
Caller: "how much is a women's cut and color?"
You: "pricing depends on the service and length — {{CLOSE_PERSON}}'ll call you back with the details. can I get your name?"
[Never quote prices. Collect name, route to callback.]`,
  },
  real_estate: {
    INDUSTRY: 'real estate office',
    PRIMARY_CALL_REASON: 'buying, selling, or listing a property',
    TRIAGE_SCRIPT: [
      `"If buying: 'awesome. are you just starting to look, or have you found a place you're interested in?'"`,
      `"If selling: 'got it. are you looking for a market assessment, or are you ready to list?'"`,
      `"If rental: 'for sure. are you looking to rent or are you a landlord looking for property management?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what area are you looking in?',
    INFO_TO_COLLECT: 'buying or selling, area of interest, budget range or property type, and preferred callback time',
    INFO_LABEL: 'property details',
    SERVICE_TIMING_PHRASE: 'set up a time to chat',
    CLOSE_PERSON: 'our agent',
    CLOSE_ACTION: 'call ya back to discuss your options and next steps',
    MOBILE_POLICY: "we can meet at our office, at the property, or do a video call — whatever works best",
    COMPLETION_FIELDS: 'buying or selling, area, and preferred callback time',
    INSURANCE_STATUS: 'no fees to chat with us',
    INSURANCE_DETAIL: "the initial consultation is free — no strings attached",
    WEEKEND_POLICY: 'yeah we work weekends too — real estate moves fast',
  },
  property_management: {
    INDUSTRY: 'property management company',
    PRIMARY_CALL_REASON: 'maintenance request, viewing inquiry, billing question, or general inquiry',
    SERVICE_APPOINTMENT_TYPE: 'maintenance visit',
    TRIAGE_SCRIPT: [
      `"If maintenance: 'got it — is this an emergency like no heat or a water leak, or more of a routine repair?'"`,
      `"If emergency maintenance (flooding, no heat, gas, fire): 'okay that sounds urgent — if you're in danger, call 9-1-1 right now. what's your name and unit?'"`,
      `"If viewing/showing: 'yes, for sure — what kind of place are you looking for?'"`,
      `"If rent or billing: 'okay — what's your name and address? i'll make sure the manager calls you back to sort that out.'"`,
      `"If general: 'got it — let me grab your name and i'll have the manager call you back.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: "what's your name?",
    INFO_TO_COLLECT: 'name, unit or property address, and reason for the call',
    INFO_LABEL: 'info',
    SERVICE_TIMING_PHRASE: 'take care of that',
    CLOSE_PERSON: 'the property manager',
    CLOSE_ACTION: 'call you back to sort that out',
    MOBILE_POLICY: 'we come to you for maintenance issues',
    COMPLETION_FIELDS: 'caller name',
    INSURANCE_STATUS: 'N/A',
    INSURANCE_DETAIL: 'N/A',
    WEEKEND_POLICY: "for emergencies like flooding, no heat, or a security issue we're reachable — for routine requests we're back monday morning",
    FORBIDDEN_EXTRA: [
      "NEVER give out the property manager's personal phone number. Route all contacts to callback.",
      "NEVER promise a specific repair timeline — always route to manager callback.",
      "NEVER confirm or deny rent amounts, unit availability, pet policy, parking, or utilities — always route to manager.",
      "NEVER give legal advice — deflect any RTA, eviction, or landlord rights questions to manager.",
      "NEVER pretend to transfer or put someone on hold. This is a callback-only service.",
      "If the caller repeats the same answer twice, NEVER ask them to elaborate further — treat it as confirmed and move to info collection.",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
MAINTENANCE / REPAIR (includes heat, plumbing, appliances, security, anything broken in the unit):
"got it — is this an emergency like no heat or a water leak, or more of a routine repair?"
→ EMERGENCY signals — flooding, burst pipe, active water leak, gas smell, electrical fire or sparks, break-in in progress, no heat:
  "okay, sounds urgent — if you're in danger, call 9-1-1 right now. what's your name and unit?"
  → collect name + unit/address + brief issue → flag [URGENT] → close fast
→ ROUTINE (broken appliance, dripping faucet, minor repair, lockout):
  collect name + unit/address + issue → close normally
SHORT / 1-WORD ANSWERS (caller gives minimal responses like "problem", "no heat", "broken"):
→ Mirror their brevity. Do NOT ask elaboration questions.
→ If it sounds urgent: "okay, flagging this urgent — what's your name and unit?"
→ If unclear: "got it — what's your name? {{CLOSE_PERSON}}'ll call you back to sort it out."
→ If they repeat the same answer: treat it as confirmed and move to info collection.
RENTAL INQUIRY / PROSPECT (saw listing on Kijiji, Marketplace, or heard about us — looking to rent):
"yes, for sure — what kind of place are you looking for?"
→ Collect: unit type (1-bed, 2-bed, etc.) + where they saw it (Kijiji, Facebook/Marketplace, etc. — ask if not mentioned) + name
→ Do NOT ask for their unit or address — they don't have one yet
→ NEVER answer questions about availability, pricing, pets, parking, or utilities — route every one to {{CLOSE_PERSON}}
BILLING / PAYMENT / RENT QUESTION:
"okay — what's your name and address? I'll make sure {{CLOSE_PERSON}} calls you back to sort that out."
→ Collect name + address + brief question summary
PERSONAL CALL / MESSAGE FOR MANAGER / CALLING FOR THE MANAGER:
"yes, {{CLOSE_PERSON}}'s tied up right now. what's your name?"
→ Collect name + brief reason
UNCLEAR / DOESN'T FIT:
"are you one of our tenants, or are you looking to rent a place?"
→ Route based on answer.`,
    INFO_FLOW_OVERRIDE: `Collect required fields — one question at a time. Do NOT ask two things at once.
For current tenants: name → unit/address → issue.
For rental prospects: what they're looking for → name.
For messages: name → reason.
After each piece of info: briefly confirm back. "got it, [repeat what they said]."
After collecting the required info, close with the callback statement below. The caller's number is already known — do NOT ask for it.`,
    CLOSING_OVERRIDE: `[COMPLETION CHECK — before closing, verify: have you collected caller name? If name is missing: "what's your name?" Do NOT use closing language until name is confirmed.]
Briefly confirm what was logged — one short sentence only, then the standard close:
→ maintenance: "got it [name], I've flagged that for {{CLOSE_PERSON}}."
→ rental inquiry: "got it [name], I've noted you're looking for a [type]."
→ billing/payment: "got it [name], I've logged your question for {{CLOSE_PERSON}}."
→ message/personal: "got it [name], I'll pass that along."
Then: "{{CLOSE_PERSON}}'ll call you back at the number you called from. talk to you soon." then use hangUp tool IMMEDIATELY — say nothing more.`,
    NICHE_EXAMPLES: `Example A — Emergency maintenance (no heat in winter):
Caller: "my furnace stopped working, it's freezing in here"
You: "oh no — okay, flagging this urgent right now. what's your name and unit number?"
Caller: [name and unit]
You: "got it — {{CLOSE_PERSON}}'s on this right away. talk to you soon." [use hangUp — flag [URGENT]]
[No heat = always URGENT. Skip diagnosis questions. Flag urgent → name + unit → close. Every extra question risks losing the caller.]

Example B — Rental prospect from listing:
Caller: "hi, i saw your 2-bedroom listing — is it still available?"
You: "got it, you're looking at the 2-bedroom — {{CLOSE_PERSON}} will call you back with availability and all the details. what's your name?"
Caller: [name]
You: "perfect, {{CLOSE_PERSON}} will be in touch. talk to you soon." [use hangUp]
[NEVER answer availability, price, pets, parking, utilities. Route every listing question to callback.]

Example C — Caller wants to speak to manager:
Caller: "can I speak to the manager please?"
You: "yes, {{CLOSE_PERSON}}'s tied up right now — what's your name?"
Caller: [gives info]
You: "perfect, {{CLOSE_PERSON}} will call you back. talk to you soon." [use hangUp]
[If they refuse to give info: "no problem, {{CLOSE_PERSON}} will call you back." then hangUp immediately. Never push twice.]

Example D — Billing / rent question:
Caller: "i have a question about my rent payment this month"
You: "got it — what's your name and address?"
Caller: [name and unit]
You: "perfect — {{CLOSE_PERSON}} will call you back to sort that out. talk to you soon." [use hangUp]
[Never discuss payment amounts, methods, or due dates. Collect info, route to callback.]

Example E — Gas leak (life safety):
Caller: "I can smell gas in my apartment"
You: "okay — call your gas company emergency line or 9-1-1 right now and get out of the building. what's your name and unit so {{CLOSE_PERSON}} can follow up?"
Caller: [info]
You: "got it — get out now and call 9-1-1. {{CLOSE_PERSON}} will follow up right away." [use hangUp — flag [URGENT]]
[Life safety = 9-1-1 first, always. Still collect info for follow-up.]

Example F — Spam robocall:
Caller: [pre-recorded voice] "...your vehicle's extended warranty is about to expire..."
You: "thanks, not interested. have a good day." [use hangUp immediately — do not engage]`,
    FILTER_EXTRA: `SERVICES NOT OFFERED (commercial properties):
"we're residential only — but I can have {{CLOSE_PERSON}} call you back to point you in the right direction." then use hangUp tool.`,
  },
  outbound_isa_realtor: {
    INDUSTRY: 'real estate team',
    PRIMARY_CALL_REASON: 'following up on a real estate inquiry',
    TRIAGE_SCRIPT: [
      `"If interested: 'awesome — are you looking to buy, sell, or both?'"`,
      `"If not interested: 'no worries at all — is there a better time to follow up, or would you prefer i take you off the list?'"`,
      `"If callback requested: 'of course — when's the best time and number for our agent to reach you?'"`,
      `"If wrong person: 'sorry about that — i'll make a note and won't call again.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'are you currently looking to buy or sell?',
    INFO_TO_COLLECT: 'buying or selling, area of interest, current status (just browsing / actively searching / ready now), and best callback time',
    INFO_LABEL: 'contact details',
    SERVICE_TIMING_PHRASE: 'set up a quick call',
    CLOSE_PERSON: 'our agent',
    CLOSE_ACTION: 'call ya back for a quick 10-minute chat',
    MOBILE_POLICY: 'we work across the whole area — in-person, virtual, or by phone',
    COMPLETION_FIELDS: 'interest level, buying or selling, and best callback time confirmed',
    INSURANCE_STATUS: 'N/A',
    INSURANCE_DETAIL: 'N/A',
    WEEKEND_POLICY: "yeah we work weekends too — real estate doesn't stop on saturdays",
  },
  voicemail: {
    INDUSTRY: 'professional practice',
    PRIMARY_CALL_REASON: 'reaching {{BUSINESS_NAME}}',
    TRIAGE_SCRIPT: [
      `"If urgent: 'okay, got it — let me make sure i have the right details to pass along.'"`,
      `"If unclear reason: 'no worries — just give me a quick idea of what it's about so they know when they call back.'"`,
      `"If wrong number: 'no problem — sorry about that, i'll make a note.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: "can i get your name and what this is about?",
    INFO_TO_COLLECT: 'name and reason for the call',
    INFO_LABEL: 'message details',
    SERVICE_TIMING_PHRASE: 'pass your message along',
    CLOSE_PERSON: '{{BUSINESS_NAME}}',
    CLOSE_ACTION: 'get back to you as soon as possible',
    MOBILE_POLICY: 'N/A',
    COMPLETION_FIELDS: 'name and reason for call',
    INSURANCE_STATUS: 'N/A',
    INSURANCE_DETAIL: 'N/A',
    WEEKEND_POLICY: "i'll make sure your message gets through",
  },
  print_shop: {
    INDUSTRY: 'print shop',
    PRIMARY_CALL_REASON: 'a printing quote, order, or question',
    TRIAGE_SCRIPT: [
      `"If quote / new order: 'for sure — what are you looking to get printed?'"`,
      `"If reorder: 'easy — do you remember roughly what it was? size, quantity, that kind of thing?'"`,
      `"If order status / is it ready?: 'i can't pull up orders from here, but i'll have someone check and call ya back. what's your name?'"`,
      `"If design question: 'yeah we've got a designer on site — do you have artwork already, or starting from scratch?'"`,
      `"If caller asks for a specific staff member by name: 'they're not at the desk right now — let me grab your info and make sure they get the message.'"`,
      `"If unsure what they need: 'no worries — tell me a bit about what you're trying to do and we'll figure out the right product.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what are you looking to get printed?',
    INFO_TO_COLLECT: 'product type, size or quantity, and whether artwork is ready',
    INFO_LABEL: 'order details',
    SERVICE_TIMING_PHRASE: 'come pick it up',
    CLOSE_PERSON: 'the team',
    CLOSE_ACTION: 'call ya back to get the order sorted',
    MOBILE_POLICY: "pickup only — we don't do delivery or shipping",
    COMPLETION_FIELDS: 'product type, approximate size or quantity, and artwork status',
    INSURANCE_STATUS: 'cash or card',
    INSURANCE_DETAIL: "pay when you pick up — easy as that",
    WEEKEND_POLICY: "we're closed weekends — leave a message and we'll call ya back first thing Monday",
    URGENCY_KEYWORDS: '"deadline today", "event tomorrow", "i need it today", "same-day rush", "it\'s for this weekend", "need it printed today", "event is tomorrow"',
    sms_template: "Thanks for calling {{business}}! Place your order https://{{niche_websiteUrl}}/ online or send your files anytime: {{niche_emailAddress}} — the team will call you back shortly.",
  },
  barbershop: {
    INDUSTRY: 'barbershop',
    PRIMARY_CALL_REASON: 'appointment booking or service inquiry',
    SERVICE_APPOINTMENT_TYPE: 'appointment',
    TRIAGE_SCRIPT: [
      `"If booking: 'for sure — what are you coming in for? a cut, beard trim, something else?'"`,
      `"If walk-in question: 'yeah, walk-ins are welcome — just can't promise the wait. want me to grab you a slot right now?'"`,
      `"If price question: 'cuts start from {{PRICE_RANGE}} — {{CLOSE_PERSON}} confirms the exact total when you're in. wanna book a slot?'"`,
      `"If group booking (3+ people): '{{CLOSE_PERSON}} handles group bookings directly — can i get your name and number?'"`,
      `"If cancellation/reschedule: 'no worries — what's your name and when was your appointment?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what service are you coming in for?',
    INFO_TO_COLLECT: 'service wanted, preferred day and time, any barber preference, and callback number',
    INFO_LABEL: 'booking details',
    SERVICE_TIMING_PHRASE: 'come in',
    CLOSE_PERSON: 'the owner',
    CLOSE_ACTION: 'call ya back to confirm the booking',
    MOBILE_POLICY: "you'd come in to us",
    COMPLETION_FIELDS: 'caller name, service needed, preferred day and time, and callback number',
    INSURANCE_STATUS: 'N/A',
    INSURANCE_DETAIL: 'N/A',
    WEEKEND_POLICY: "yeah we're usually open saturdays — {{CLOSE_PERSON}} can confirm the exact hours",
    URGENCY_KEYWORDS: '"today", "tonight", "wedding", "event tonight", "need it today", "asap", "right now", "same day"',
    sms_template: "Thanks for calling {{business}}! We'll be in touch to confirm your appointment.",
    PRICE_RANGE: 'contact us for pricing',
    WALK_IN_POLICY: 'walk-ins are welcome',
    FORBIDDEN_EXTRA: [
      "NEVER promise appointment availability or confirm a time without using checkCalendarAvailability or routing to {{CLOSE_PERSON}}.",
      "NEVER guarantee a specific barber will be available.",
      "NEVER quote walk-in wait times — only the owner knows the current queue.",
      "NEVER give hair care advice, styling recommendations, or color treatment guidance.",
      "GROUP BOOKING (3+ people, wedding party, sports team): do NOT use calendar tool. Route to owner directly — collect name and phone only.",
      "If checkCalendarAvailability returns fallback=true: switch to message-taking mode — 'let me take your info and have {{CLOSE_PERSON}} call ya back to confirm the timing.'",
      "If bookAppointment returns booked=false with reason slot_taken: 'that one just got taken — the next opening's at [nextAvailable]. want me to grab that one?'",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.

BOOKING REQUEST:
"for sure — what are you coming in for? a cut, beard trim, something else?"
→ Collect: service type + preferred day/time + barber preference (if any) → booking flow or info collection

WALK-IN QUESTION:
"yeah, {{WALK_IN_POLICY}} — just can't promise the wait. if you wanna skip the line, i can grab you a slot right now."
→ If yes: move into full booking flow
→ If no: "no worries — just come on in whenever."

PRICE QUESTION:
"yeah, cuts start from {{PRICE_RANGE}} — {{CLOSE_PERSON}} confirms the exact total when you're in depending on the style."
→ Then: "wanna book a slot while you're on?"

SAME-DAY / URGENT CUT:
"got ya — let me check what's open today."
→ Use checkCalendarAvailability with today's date. Flag as URGENT.

SPECIFIC BARBER REQUEST:
"i can't check the individual schedule from here — i'll note that you prefer [barber name] and {{CLOSE_PERSON}} will do their best to accommodate."
→ Add preference to booking description. Continue to booking flow.

GROUP BOOKING (3 or more people, wedding party, team):
"a group booking — nice. {{CLOSE_PERSON}} handles those directly so they can block the right amount of time. can i get your name and a good number?"
→ Collect name + callback. Do NOT attempt calendar booking.

CANCELLATION / RESCHEDULE:
"no worries — what's your name and when was your appointment? i'll let {{CLOSE_PERSON}} know and they'll get it sorted."
→ Take info only. Do NOT modify the calendar.`,
    NICHE_EXAMPLES: `Example A — Live booking (calendar connected):
Caller: "hi, i need a haircut"
You: "gotcha — what day works for ya?"
Caller: "Friday"
You: "let me check Friday real quick... i've got openings at 10am, 1pm, and 3:30 — any of those?"
Caller: "1pm"
You: "perfect — and your name?"
Caller: "Jake"
You: "you're booked Jake, Friday at 1. see ya then!" [use hangUp]

Example B — Calendar fallback (message mode):
Caller: "can i book a beard trim for Saturday?"
You: "for sure — what time were you thinking?"
Caller: "around 11"
You: "got it. let me take your info and have {{CLOSE_PERSON}} call ya back to confirm — what's the best number?"
[Collect name + callback. Mark as WARM.]

Example C — Walk-in question converts to booking:
Caller: "can i just walk in today?"
You: "yeah, walk-ins are welcome — just can't guarantee the wait. want me to grab you a slot right now?"
Caller: "yeah sure"
You: "awesome — what are you coming in for?"
[Move into booking flow. Mark as WARM.]

Example D — Same-day urgent cut:
Caller: "i need a cut today — i've got a wedding tonight"
You: "got ya — let me check what's open today."
[checkCalendarAvailability for today. Read back slots. Book immediately. Mark as HOT.]

Example E — Specific barber request:
Caller: "i only want Marcus, is he in?"
You: "i can't check the individual schedule from here — i'll note that you want Marcus. what day were you thinking?"
[Collect day, run booking flow, add preference to description. Mark as WARM.]

Example F — Spam / telemarketer:
Caller: [pitch voice] "Hi, this is Sarah from Marketing Solutions—"
You: "thanks, we're all set." [use hangUp immediately — do not engage]`,
  },
  restaurant: {
    INDUSTRY: 'restaurant',
    PRIMARY_CALL_REASON: 'menu questions, ordering, hours, or reservations',
    SERVICE_APPOINTMENT_TYPE: 'reservation',
    TRIAGE_SCRIPT: [
      `"If menu question: 'for sure — what are you curious about? i can help with that.'"`,
      `"If ordering (phone orders accepted): 'yeah, we take phone orders. what can i get started for ya?'"`,
      `"If ordering (phone orders NOT accepted): 'we don't take orders over the phone — easiest way is through our app or website. i can pass along a message if you need anything else.'"`,
      `"If hours: 'yeah we're open {{HOURS_WEEKDAY}}. anything i can help you with today?'"`,
      `"If reservation: 'for sure — i'll have the team call you back to confirm. what's your name and how many people?'"`,
      `"If catering: 'for sure — catering inquiry. i'll have someone call you back with all the details. what's your name?'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: "what can i help ya with today?",
    INFO_TO_COLLECT: 'name, party size or order details, and preferred callback time',
    INFO_LABEL: 'contact info',
    SERVICE_TIMING_PHRASE: 'come in',
    CLOSE_PERSON: 'the team',
    CLOSE_ACTION: 'call ya back to sort that out',
    MOBILE_POLICY: "you'd come in to us or order through our app",
    COMPLETION_FIELDS: 'name and reason for call',
    INSURANCE_STATUS: 'cash or card',
    INSURANCE_DETAIL: "we keep it simple — pay when you pick up or dine in",
    WEEKEND_POLICY: "yeah we're open weekends — hours may vary so call ahead if you're not sure",
    FORBIDDEN_EXTRA: [
      "NEVER confirm reservation availability — always route to team callback for confirmation.",
      "NEVER quote wait times or guarantee a table — always route to team callback.",
      "NEVER discuss catering pricing in detail — route to team callback.",
    ].join('\n'),
    TRIAGE_DEEP: `Listen to what they say and route naturally.
MENU QUESTION:
"for sure — what are you curious about?"
→ Answer from context data if available. If not: "i'll have the team call you back with the details."
ORDERING (if phone orders accepted):
"yeah, we take phone orders. what can i get started for ya?"
→ Collect: items + name + callback number (if delivery) → close
HOURS / ARE YOU OPEN:
"yeah we're open {{HOURS_WEEKDAY}}. anything i can help with today?"
→ If no further question: "alright, take care." then use hangUp tool.
RESERVATION:
"for sure — what's your name and how many people?"
→ Collect: name + party size + preferred date/time → close
CATERING INQUIRY:
"for sure — catering. let me grab your name and the team will call you back with everything."
→ Collect: name + event date/size → close`,
    NICHE_EXAMPLES: `Example A — Menu question:
Caller: "do you have vegetarian options?"
You: "yeah, for sure — we've got a few. what kind of thing are you looking for?"
Caller: "like pasta or salads"
You: "got it — we've got options like that. best to check the full menu when you come in or I can have the team call you back. what's your name?"

Example B — Reservation request:
Caller: "can I make a reservation for saturday night?"
You: "for sure — what's your name and how many people?"
Caller: [name and party size]
You: "perfect — the team will call you back to confirm your reservation. talk soon." [use hangUp]

Example C — Catering inquiry:
Caller: "I'm looking for catering for a company lunch"
You: "nice — how many people are you thinking, and what's your name?"
Caller: [name and count]
You: "got it — the team will call you back with pricing and all the details. talk soon." [use hangUp]

Example D — Hours question (caller done after):
Caller: "what are your hours on sunday?"
You: "yeah we're open {{HOURS_WEEKDAY}}. anything else i can help with today?"
Caller: "no that's all, thanks"
You: "talk soon!" [use hangUp immediately]`,
    sms_template: "Thanks for calling {{business}}! Check our menu and order online or call us back during business hours.",
  },
  other: {
    INDUSTRY: 'business',
    PRIMARY_CALL_REASON: 'service or inquiry',
    SERVICE_APPOINTMENT_TYPE: 'appointment',
    TRIAGE_SCRIPT: [
      `"If clear request: 'gotcha. let me grab a few details so we can help ya out.'"`,
      `"If unclear: 'no worries — tell me a bit about what you need and we'll figure it out.'"`,
    ].join('\n'),
    FIRST_INFO_QUESTION: 'what can we help you with today?',
    INFO_TO_COLLECT: 'what they need, their name, and preferred callback time',
    INFO_LABEL: 'details',
    SERVICE_TIMING_PHRASE: 'get that set up',
    CLOSE_PERSON: 'our team',
    CLOSE_ACTION: 'call ya back to take care of everything',
    MOBILE_POLICY: "depends on the service — we'll sort that out when we call back",
    COMPLETION_FIELDS: 'what they need and preferred callback time',
    INSURANCE_STATUS: 'cash or card',
    INSURANCE_DETAIL: 'we keep it simple',
    WEEKEND_POLICY: "we're open most weekends — call back and we'll see what we can do",
  },
}
