/**
 * phase1-extract.ts — ONE-SHOT Phase 1 extraction script.
 *
 * Run: npx tsx src/lib/__tests__/phase1-extract.ts
 *
 * What it does:
 *   1. Reads prompt-builder.ts
 *   2. Creates src/lib/prompt-config/*.ts files (5 new modules)
 *   3. Rewrites prompt-builder.ts to import from those modules
 *
 * Delete this file after Phase 1 is committed.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SRC = join(__dirname, '..') // src/lib/
const BUILDER = join(SRC, 'prompt-builder.ts')
const CONFIG_DIR = join(SRC, 'prompt-config')

mkdirSync(CONFIG_DIR, { recursive: true })

const src = readFileSync(BUILDER, 'utf8')
const lines = src.split('\n')

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Extract lines [start, end] inclusive (1-based). */
function extractLines(start: number, end: number): string {
  return lines.slice(start - 1, end).join('\n')
}

/** Write a new config file. */
function writeConfig(filename: string, content: string): void {
  writeFileSync(join(CONFIG_DIR, filename), content, 'utf8')
  console.log(`  created prompt-config/${filename}`)
}

// ── 1. template-body.ts (lines 29-288) ───────────────────────────────────────
// The block starts with: const INBOUND_TEMPLATE_BODY = `...`
// We need to add 'export' and strip the leading 'const '.

const templateBlock = extractLines(29, 288)
// Line 29 is: "const INBOUND_TEMPLATE_BODY = `..."
// Replace the leading `const ` with `export const `
const templateContent = templateBlock.replace(/^const INBOUND_TEMPLATE_BODY/, 'export const INBOUND_TEMPLATE_BODY')

writeConfig('template-body.ts', [
  '// Generated by phase1-extract.ts — DO NOT EDIT manually.',
  '// Source: prompt-builder.ts lines 29-288',
  '',
  templateContent,
  '',
].join('\n'))

// ── 2. insurance-presets.ts (lines 292-344) ──────────────────────────────────

const insuranceBlock = extractLines(292, 344)
// Add export to all three consts
const insuranceContent = insuranceBlock
  .replace(/^const INSURANCE_PRESETS/, 'export const INSURANCE_PRESETS')
  .replace(/^const PRICING_POLICY_MAP/, 'export const PRICING_POLICY_MAP')
  .replace(/^const UNKNOWN_ANSWER_MAP/, 'export const UNKNOWN_ANSWER_MAP')

writeConfig('insurance-presets.ts', [
  '// Generated by phase1-extract.ts — DO NOT EDIT manually.',
  '// Source: prompt-builder.ts lines 292-344',
  '',
  insuranceContent,
  '',
].join('\n'))

// ── 3. niche-defaults.ts (lines 352-1160) ────────────────────────────────────
// Includes the NicheDefaults type + NICHE_DEFAULTS export

const nicheBlock = extractLines(352, 1160)

writeConfig('niche-defaults.ts', [
  '// Generated by phase1-extract.ts — DO NOT EDIT manually.',
  '// Source: prompt-builder.ts lines 352-1160',
  '',
  nicheBlock,
  '',
].join('\n'))

// ── 4. niche-classification.ts (lines 1162-1178) ─────────────────────────────

const classificationBlock = extractLines(1162, 1178)

writeConfig('niche-classification.ts', [
  '// Generated by phase1-extract.ts — DO NOT EDIT manually.',
  '// Source: prompt-builder.ts lines 1162-1178',
  '',
  classificationBlock,
  '',
].join('\n'))

// ── 5. mode-overrides.ts (lines 1888-1921) ───────────────────────────────────

const modeBlock = extractLines(1888, 1921)
// Add export to MODE_VARIABLE_OVERRIDES
const modeContent = modeBlock.replace(/^const MODE_VARIABLE_OVERRIDES/, 'export const MODE_VARIABLE_OVERRIDES')

writeConfig('mode-overrides.ts', [
  '// Generated by phase1-extract.ts — DO NOT EDIT manually.',
  '// Source: prompt-builder.ts lines 1888-1921',
  '',
  modeContent,
  '',
].join('\n'))

// ── Rewrite prompt-builder.ts ─────────────────────────────────────────────────

console.log('\n  rewriting prompt-builder.ts...')

// Build the new file by:
// 1. Adding imports for all 5 new modules after the existing imports block
// 2. Replacing each extracted block with a comment

let out = src

// Replace INBOUND_TEMPLATE_BODY declaration (lines 26-288) with import
// Block starts with "// ── Embedded template body" comment at line 26
const templateStart = out.indexOf('// ── Embedded template body ───')
// Block ends at the closing backtick + newline on line 288
const templateEndStr = "---`\n\n// ── Insurance presets"
const templateEndIdx = out.indexOf(templateEndStr)
if (templateStart === -1 || templateEndIdx === -1) throw new Error('Could not find template body block boundaries')
out = out.slice(0, templateStart) +
  "import { INBOUND_TEMPLATE_BODY } from './prompt-config/template-body'\n" +
  out.slice(templateEndIdx + "---`\n".length)

// Replace INSURANCE_PRESETS + PRICING_POLICY_MAP + UNKNOWN_ANSWER_MAP block
const insuranceStart = out.indexOf('// ── Insurance presets ───')
const insuranceEndMarker = "// ── Voice style presets"
const insuranceEndIdx = out.indexOf(insuranceEndMarker)
if (insuranceStart === -1 || insuranceEndIdx === -1) throw new Error('Could not find insurance block boundaries')
out = out.slice(0, insuranceStart) +
  "import { INSURANCE_PRESETS, PRICING_POLICY_MAP, UNKNOWN_ANSWER_MAP } from './prompt-config/insurance-presets'\n\n" +
  out.slice(insuranceEndIdx)

// Replace NicheDefaults type + NICHE_DEFAULTS block
const nicheTypeStart = out.indexOf('// ── Per-niche defaults (all 22 template variables) ───')
const nicheEndMarker = '// ── Per-niche classification rules'
const nicheEndIdx = out.indexOf(nicheEndMarker)
if (nicheTypeStart === -1 || nicheEndIdx === -1) throw new Error('Could not find niche-defaults block boundaries')
out = out.slice(0, nicheTypeStart) +
  "import { type NicheDefaults, NICHE_DEFAULTS } from './prompt-config/niche-defaults'\n\n" +
  out.slice(nicheEndIdx)

// Replace NICHE_CLASSIFICATION_RULES block
const classStart = out.indexOf('// ── Per-niche classification rules (for call classifier) ───')
const classEndMarker = '// ── Per-niche FAQ defaults'
const classEndIdx = out.indexOf(classEndMarker)
if (classStart === -1 || classEndIdx === -1) throw new Error('Could not find classification block boundaries')
out = out.slice(0, classStart) +
  "import { NICHE_CLASSIFICATION_RULES } from './prompt-config/niche-classification'\n\n" +
  out.slice(classEndIdx)

// Replace MODE_VARIABLE_OVERRIDES block
// It starts with the Phase 2b comment above it
const modeBlockStart = out.indexOf('// Phase 2b scope: build-time only.')
const modeEndMarker = '\n/**\n * Apply agent-mode-level variable defaults'
const modeEndIdx = out.indexOf(modeEndMarker)
if (modeBlockStart === -1 || modeEndIdx === -1) throw new Error('Could not find mode-overrides block boundaries')
out = out.slice(0, modeBlockStart) +
  "import { MODE_VARIABLE_OVERRIDES } from './prompt-config/mode-overrides'\n" +
  out.slice(modeEndIdx)

writeFileSync(BUILDER, out, 'utf8')
console.log('  prompt-builder.ts rewritten')
console.log('\nPhase 1 extraction complete. Run tests to verify.')
